version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
    env_file:
      - var.env
